# These are supported funding model platforms

github: mathisgauthey
custom: ["https://www.paypal.com/donate/?hosted_button_id=7Z9AFY6SXMCJ2"]
custom: ["https://www.paypal.me/mathisgauthey"]
ko_fi: mathisgauthey
custom: ["https://www.buymeacoffee.com/mathisgauthey"]
