# These are supported funding model platforms

ko_fi: mathisgauthey
custom: ["https://www.buymeacoffee.com/mathisgauthey","https://www.paypal.com/donate/?hosted_button_id=7Z9AFY6SXMCJ2", "https://www.paypal.me/mathisgauthey", "https://www.blockchain.com/btc/address/bc1q8qhuwm2050kjc7pa8h645xpz7ghkde07jc5w80"]
